### Numpy Start

In [3]:
import numpy as np

In [4]:
a = np.array(1)
a

array(1)

In [5]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [6]:
ndarr_2 = np.array([1,2.0,3]) #float 형식
print(ndarr_2)

[1. 2. 3.]


In [7]:
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3)

['1' '2.0' '3']


### 배열의 정보 확인

In [8]:
#ndarray.dtype (자료형 확인 속성)
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [9]:
print(np.array(1 + 2j).dtype)
print(np.array(print).dtype)

complex128
object


### 자료형 지정

In [10]:
dtype1 = np.array([1,2,3],dtype=np.int8)
print(dtype1.dtype)

int8


In [11]:
dtype2 = np.array([1,2,3],dtype=float)
print(dtype2.dtype)

float64


In [12]:
dtype3 = np.array([1,2,3],dtype=str)
print(dtype3.dtype)

<U1


- 주의해야할 점

In [13]:
dtype4 = np.array([1,2,3],dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [14]:
dtype5 = np.array([1,'data',print],dtype=float)
print(dtype5.dtype)

ValueError: could not convert string to float: 'data'

### 배열의 정보 확인

In [ ]:
# 배열 크기 확인
# ndarray.shape
print(ndarr_1.shape)

(3,)


In [ ]:
# 배열 차원 확인
# ndarray.ndim
print(ndarr_1.ndim)

1


### N차원 배열
- Scalar : 숫자
- Vector : scalar의 배열, 1차원 배열
- Matrix : vector의 배열, 2차원 배열
- Tensor : matrix의 배열, 3차원 배열 이상

- 배열생성


In [ ]:
# 1차원 배열 생성
vector = np.array([1,2,3])

print(vecter)       # 값
print(vecter.shape) # 크기
print(vecter.ndim)  # 차원
print(vecter.dtype) # 타입

[1 2 3]
(3,)
1
int32


In [ ]:
# 2차원 배열 생성
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix)       # 값
print(matrix.shape) # 크기
print(matrix.ndim)  # 차원
print(matrix.dtype) # 타입

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [ ]:
# 3차원 배열 생성
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(tensor)       # 값
print(tensor.shape) # 크기
print(tensor.ndim)  # 차원
print(tensor.dtype) # 타입

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


### 배열의 정보 확인

In [ ]:
print(tensor.size)

12


In [ ]:
# 연습문제
arr = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
2
9
(3, 3)


### 자료형 변환(리스트)

In [ ]:
# 리스트 -> ndarray 변환
list1 = [1,2,3]
arr1 = np.array(list1)
print(arr1)

[1 2 3]


In [ ]:
# ndarray -> 리스트 변환
list2 = [1,2,3]
arr2 = np.array(list2)
print(list2)

[1, 2, 3]


In [ ]:
# 2차원 리스트 변환
list3 = [[1,2,3], [4,5,6]]
arr3 = np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
# shape이 다른 리스트인 경우(주의해야할 점)
list4 = [[1,2,3,4],[5,6,7]]
arr4 = np.array(list4)
print(arr4)
print(arr4.size, arr4.shape, arr4.ndim)

[list([1, 2, 3, 4]) list([5, 6, 7])]
2 (2,) 1


C:\Users\admin\AppData\Local\Temp\ipykernel_6604\2411403213.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


### 자료형 변환(튜플) - 리스트와 동일

In [ ]:
# 튜플 -> ndarray 변환
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

[1 2 3]


In [ ]:
# ndarray -> 튜플 변환
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(arr2)

[1 2 3]


### 자료형 변환(세트, 딕셔너리)

In [15]:
# 세트 변환
set1 = {1,2,3}
arr = np.array(set1)
print(arr, arr.size, arr.shape)

{1, 2, 3} 1 ()


In [ ]:
# 딕셔너리 변환
dict1 = {'a':1,'b':2,'c':3}
arr= np.array(dict1)
print(arr)

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
set1 = {1,2,3}
arr = np.array(set1)
print(arr, arr.size, arr.shape)

{1, 2, 3} 1 ()


### 인덱싱

In [ ]:
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]

# 1가져오기
print(list_[0][0][0])
# 4가져오기
print(list_[0][1][1])
# 7가져오기
print(list_[1][1][0])

1
4
7


In [ ]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_)
# 1가져오기
print(arr_[0][0][0])
# 4가져오기
print(arr_[0][1][1])
# 7가져오기
print(arr_[1][1][0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
4
7


In [ ]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# 1가져오기
print(arr_[0,0,0])
# 4가져오기
print(arr_[0,1,1])
# 7가져오기
print(arr_[1,1,0])

1
4
7


### 배열 인덱싱

In [ ]:
arr_1 = np.array([[1,2], 
                  [3,4], 
                  [5,6]])

# 0 행 가져와서 2차원 배열 만들기
#  ndarray[[row1, row2], col]
print(arr_1[[0]])

# 0,2 행 가져와서 2차원 배열 만들기
print(arr_1[[0,2]])

# 0,1 행 가져와서 2차원 배열 만들기(col :)
print(arr_1[[0,1],:])
print(arr_1[0,1])

# 다음 결과는 ?
print(arr_1[[0,1,2],[0,1,0]])  # row1,col1 = 0,0 /row2, col2 = 1,1 / row3, col3 = 2,0

# 같은 위치 데이터 여러 번 사용가능
print(arr_1[[0,0],[1,1]])

[[1 2]]
[[1 2]
 [5 6]]
[[1 2]
 [3 4]]
2
[1 4 5]
[2 2]


In [ ]:
arr_2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

b = np.array([0,1,2,3])
c = np.array([0,2,0,1])

print(arr_2[b,c])

[ 1  6  7 11]


### Boolean 인덱싱

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])

print(arr[[True,False,True,True,False]])
print(arr[arr > 3])
arr[arr % 3 == 0]

[1 3 4]
[4 5]


array([3])

In [ ]:
score = np.array([[78, 91, 84, 89, 93, 65],
                  [82, 87, 96, 79, 91, 73]])

print(score[0][score[0] >= 90])
print(score[1][score[1] >= 90])

[91 93]
[96 91]


In [ ]:
score[1] >= 90

array([False, False,  True, False,  True, False])