### 배열 슬라이싱
#### ndarray의 슬라이싱

In [64]:
import numpy as np

In [65]:
matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20]])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [66]:
#matrix[row,col]
# 0열 전체 슬라이싱
print(matrix[:,0])

[ 1  6 11 16]


In [67]:
# 0열 전체 슬라이싱(2차원 유지)
print(matrix[:,[0]])
print(matrix[:,:1])

[[ 1]
 [ 6]
 [11]
 [16]]
[[ 1]
 [ 6]
 [11]
 [16]]


In [68]:
# 1행 전체 슬라이싱
print(matrix[1,:])

print(matrix[1]) # rank > row > col 순으로 :(콜론) 생략 가능

print(matrix[1:2,:]) # or print(matrix[[1]])

print(matrix[[1]])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]


In [69]:
# 3~4열 전체 슬라이싱
print(matrix[:,3:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [70]:
# 0행 1~3열 슬라이싱
print(matrix[0,1:4])
print(matrix[0,1:-1])

[2 3 4]
[2 3 4]


In [71]:
# 1,3행 2~4열 슬라이싱
print(matrix[[1,3],2:])

[[ 8  9 10]
 [18 19 20]]


In [72]:
# 1~2행, 1,3열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 7  9]
 [12 14]]


In [73]:
#문제 3
tensor = np.array([[[1,2,3],
                   [4,5,6]],
                   [[7,8,9],
                   [10,11,12]]])

In [74]:
# 위와 같은 2x2x3 형태의 3차원 배열을 생성하고 인덱싱을 사용해 [10 2 6] 배열을 추출해봅시다.
print(tensor[[1,0,0],[1,0,1],[0,1,2]])
tensor

[10  2  6]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
# 문제3의 tensor 배열에서 인덱싱, 슬라이싱을 사용해 [12/45], [9/12]
#12/45
print(tensor[0,:,:2])

[[1 2]
 [4 5]]


In [76]:
#[9,12]
print(tensor[1,:,2])

[ 9 12]
