# Numpy 파일 입출력

### 파일처리
- ndarray의 정보를 파일로 저장할 수 있다.
- 일반적인 파일 확장자는 npy를 사용한다.


In [12]:
import numpy as np

In [13]:
# 파일 저장(tofile)
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-0.6698156   0.5319299   0.33781848  0.41690203 -0.72076394]
 [-0.45784303  1.10043234  1.10970876  0.68150958 -0.63271789]
 [-0.09859956 -0.56077755  0.79862102  0.47041968 -0.81301277]]


In [14]:
# 파일 불러오기(fromfile)
m = np.fromfile('n.npy')
print(m)

[-0.6698156   0.5319299   0.33781848  0.41690203 -0.72076394 -0.45784303
  1.10043234  1.10970876  0.68150958 -0.63271789 -0.09859956 -0.56077755
  0.79862102  0.47041968 -0.81301277]


In [15]:
m = np.fromfile('C:/STUDY/SutdyPython_Numpy/n.npy') # shape(3,5)
print(m)

[-0.6698156   0.5319299   0.33781848  0.41690203 -0.72076394 -0.45784303
  1.10043234  1.10970876  0.68150958 -0.63271789 -0.09859956 -0.56077755
  0.79862102  0.47041968 -0.81301277]


In [16]:
# 파일 저장, 불러오기(np.save, np.load) # 행렬에 대한 정보도 가지고 있음
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-0.6698156   0.5319299   0.33781848  0.41690203 -0.72076394]
 [-0.45784303  1.10043234  1.10970876  0.68150958 -0.63271789]
 [-0.09859956 -0.56077755  0.79862102  0.47041968 -0.81301277]]


In [17]:
# n.tofile -> n.npy
# np.load('n.npy')
np.load('n.npy') # Error 파일 저장형식이 다르기 때문!

ValueError: Cannot load file containing pickled data when allow_pickle=False

### 파일 처리
- txt 파일 저장, 불러오기

In [ ]:
# txt 파일 저장(np.savetxt)
np.savetxt('n.txt',n)

In [ ]:
# txt 파일 불러오기(np.loadtxt)
np.loadtxt('n.txt')

# np.loadtxt('./data/n.txt')

array([[ 0.67355834, -0.94162996, -0.12369967,  0.24027748, -0.07535178],
       [ 0.12362399, -0.3317201 ,  0.05009873, -1.05700837, -1.15292173],
       [ 0.36546796,  0.60684358, -0.16101157, -0.0778018 ,  0.28499247]])

In [ ]:
# csv 파일 저장, 불러오기

np.savetxt('n.csv',n) # 확장자만 csv로 바꾸면 됨

In [ ]:
np.savetxt('n.csv',n, delimiter = ',')

In [ ]:
np.loadtxt('n.csv', delimiter= ',', dtype=str)

array([['6.735583417926885863e-01', '-9.416299558623338894e-01',
        '-1.236996661219502552e-01', '2.402774812598412191e-01',
        '-7.535177641145704430e-02'],
       ['1.236239862318083277e-01', '-3.317201042935186694e-01',
        '5.009872996211604812e-02', '-1.057008369890093169e+00',
        '-1.152921727883687186e+00'],
       ['3.654679637584956065e-01', '6.068435844325968942e-01',
        '-1.610115673040299067e-01', '-7.780180369190797807e-02',
        '2.849924740007636070e-01']], dtype='<U25')

In [ ]:
np.savetxt('n.csv',n, delimiter = '***')

In [ ]:
np.loadtxt('n.csv', delimiter='***')

array([[ 0.67355834, -0.94162996, -0.12369967,  0.24027748, -0.07535178],
       [ 0.12362399, -0.3317201 ,  0.05009873, -1.05700837, -1.15292173],
       [ 0.36546796,  0.60684358, -0.16101157, -0.0778018 ,  0.28499247]])

In [ ]:
# 문제1
t1 = np.array(range(1,26)).reshape(5,5)
print(t1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
np.savetxt('data.csv', t1, delimiter=',')

In [ ]:
np.loadtxt('data.csv', delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [ ]:
# 문제2
arr1 = np.loadtxt('./data/06_data1.txt', dtype=str)
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [ ]:
# 문제3
arr2 = np.loadtxt('./data/06_data2.txt', delimiter=',')
print(arr2)

[[ 1. 15. 14.  4.]
 [12.  6.  7.  9.]
 [ 8. 10. 11.  5.]
 [13.  3.  2. 16.]]


In [ ]:
# 해설 정답
# 문제1
arr = np.arange(1,26, dtype=np.int8).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [ ]:
np.savetxt('data.csv', arr, delimiter=',')

In [ ]:
np.loadtxt('data.csv', delimiter=',', dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [ ]:
np.loadtxt('./data/06_data1.txt', dtype=np.str_)

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [ ]:
np.loadtxt('./data/06_data1.txt', delimiter='\t', dtype=np.str_)

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [ ]:
arr2 = np.loadtxt('./data/06_data2.txt', delimiter=',', dtype=np.int8)

In [ ]:
print(arr2)

[[ 1 15 14  4]
 [12  6  7  9]
 [ 8 10 11  5]
 [13  3  2 16]]


### 파일처리
- 문제1) ex1 파일을 사용하여 데이터 처리

In [21]:
# 01. 파일 읽어오기

data = np.loadtxt('./data/ex1_지역별전기요금.csv', delimiter=',', dtype=int)
print(data)

# 상위 5개 데이터 출력(data[row,col])

print(data[:5,:]) 

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]
 [      6  668623     364   35245]
 [      7  425659     344   32331]
 [      8  947300     366   36274]
 [      9 2737725     361   36569]
 [     10   49394     580   57091]
 [     11  323151     353   35470]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [     14  634696     285   28556]
 [     15  258605     221   22180]
 [     16  742285     282   27901]
 [     17  584500     268   26899]]
[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [22]:
# 02. 데이터 확인하기

# 데이터 모양 확인
print(data.shape)

# 중복 지역 확인
print(np.unique(data[:,0]))

(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [23]:
# 데이터의 크기순 정렬(argsort 사용)
print(data[:,1].argsort())

# fancy index
print(data[data[:,1].argsort()])

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]
[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


In [ ]:
print(np.sort(data)) # sort / argsort 한가지 행, 열에는 사용 / 2차원 배열에서는 사용 X

[[      1     273   27177  565082]
 [      2     444   45111 2827233]
 [      3     289   29043 1144913]
 [      4     230   22436 1131034]
 [      5     391   38020  380425]
 [      6     364   35245  668623]
 [      7     344   32331  425659]
 [      8     366   36274  947300]
 [      9     361   36569 2737725]
 [     10     580   49394   57091]
 [     11     353   35470  323151]
 [     12     398   40049  734723]
 [     13     249   25120  726699]
 [     14     285   28556  634696]
 [     15     221   22180  258605]
 [     16     282   27901  742285]
 [     17     268   26899  584500]]


In [24]:
# 내림차순
print(data[:,1].argsort()[::-1])

print(data[data[:,1].argsort()[::-1]])

[ 1  8  2  3  7 15 11 12  5 13 16  0  6  4 10 14  9]
[[      2 2827233     444   45111]
 [      9 2737725     361   36569]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      8  947300     366   36274]
 [     16  742285     282   27901]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [      6  668623     364   35245]
 [     14  634696     285   28556]
 [     17  584500     268   26899]
 [      1  565082     273   27177]
 [      7  425659     344   32331]
 [      5  380425     391   38020]
 [     11  323151     353   35470]
 [     15  258605     221   22180]
 [     10   49394     580   57091]]


In [63]:
# 03.데이터 통계

# 전국 대상 가구수의 합

print(data[:,1].sum()) 
print(np.sum(data[:,1])) # 다른 표현

# 가구당 평균 전력 사용량의 전국 평균값

print(np.mean(data[:,2]))
print(round(np.mean(data[:,2]),2))

print(round(data[:,2].mean(),2)) #다른 표현

14882047
14882047
335.1764705882353
335.18
335.18


In [49]:
# 무식하게 평균 구하기
e_sum = np.sum(data[:,2])
e_sum

n_rows = data.shape[0]
n_rows

print('가구당 평균 전력 사용량의 전국 평균값 :', round(e_sum/n_rows , 2))

가구당 평균 전력 사용량의 전국 평균값 : 335.18


In [51]:
# 가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg_ = data[:,2].mean() # 가구당 평균 전력 사용량의 전국 평균


print(data[data[:,2]>avg_, 0:2])


[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


In [64]:
avg_ = np.mean(data[:,2])
avg_

335.1764705882353

In [65]:
print(data[data[:,2] > avg_, 0:2])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


# 파일처리(문제)
- 문제2) ex2_전년대비_시도별_교통사망사고.csv

### [문제1] 위 파일을 읽어보고 상위 3개의 (발생년도, 발생건수, 구성비)의 데이터를 추출해 봅시다.

In [155]:
acc_data = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv', delimiter=',', dtype=np.int32)

acc_data[:,2].argsort()
max_acc = acc_data[acc_data[:,2].argsort()[::-1]]

print(max_acc[:3,0:4])

[[2014    2  872   19]
 [2014    4  464   10]
 [2014    3  401    8]]


### [문제2] 위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출해 봅시다.


In [97]:
print('부산에서 발생한 교통사망사고 현황 :', acc_data[7,:])

부산에서 발생한 교통사망사고 현황 : [2014    8  163    3  -47  -22]


### [문제3] 위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산해 봅시다.

In [106]:
print('전국 사고 발생건수의 합계 :' , np.sum(acc_data[:,2]), '건')
print('전국 사고 발생건수의 평균 :', round(np.mean(acc_data[:,2]),2), '건')

전국 사고 발생건수의 합계 : 4583 건
전국 사고 발생건수의 평균 : 269.59 건


### [문제4] 위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [125]:
max_Num = acc_data[np.argmax(acc_data[:,4])]

print('증감수가 가장 큰 지역 : 대구', max_Num)

증감수가 가장 큰 지역 : 대구 [2014    6  182    4   19   11]


### [문제5] 위 데이터에서 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출해 봅시다.

In [130]:
min_Rate = acc_data[np.argmin(acc_data[:,5])]

print('증감수가 가장 작은 지역 부산:', min_Rate)

증감수가 가장 작은 지역 부산: [2014    8  163    3  -47  -22]


### [문제6] 위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출해 봅시다.

In [142]:
print(acc_data[acc_data[:,2] >= 400])

[[2014    2  872   19  -45   -4]
 [2014    3  401    8  -45  -10]
 [2014    4  464   10  -41   -8]
 [2014   13  400    8  -35   -8]]


# 문제 해답

In [151]:
# 문제 1
data = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv', delimiter=',', dtype=float)

data.shape

np.unique(data[:,1])

print(data[:3,[0,2,3]])


[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


In [160]:
# 문제 2
data[7, 1:]

print(data[7])

data[data[:,1] == 8]

print(data[data[:,1] == 8])

[2014.     8.   163.     3.6  -47.   -22.4]
[[2014.     8.   163.     3.6  -47.   -22.4]]


In [164]:
# 문제 3
print('전국 사고 발생건수의 합계 :' , data[:,2].sum(), '건')
print('전국 사고 발생건수의 평균 :', round(data[:,2].mean(),3), '건')

전국 사고 발생건수의 합계 : 4583.0 건
전국 사고 발생건수의 평균 : 269.588 건


In [171]:
# 문제 4

# 방법1
max(data[:,4])
print(data[data[:,4] == max(data[:,4])])

# 방법2
np.argmax(data[:,4])
print(data[np.argmax(data[:,4])])



[[2014.     6.   182.     4.    19.    11.7]]
[2014.     6.   182.     4.    19.    11.7]


In [174]:
# 문제 5

# 방법 1
min(data[:,5])
print(data[data[:,5] == min(data[:,5])])

# 방법2
print(data[np.argmin(data[:,5])])

[[2014.     8.   163.     3.6  -47.   -22.4]]
[2014.     8.   163.     3.6  -47.   -22.4]


In [189]:
# 문제 6

data2 = data[data[:,2] >= 400]
data2
# 1,2,4,5 만 추출
print(data2[ : , [1,2,4,5]])

print(data[data[:,2] >= 400][:,[1,2,4,5]])

[[  2.  872.  -45.   -4.9]
 [  3.  401.  -45.  -10.1]
 [  4.  464.  -41.   -8.1]
 [ 13.  400.  -35.   -8. ]]
[[  2.  872.  -45.   -4.9]
 [  3.  401.  -45.  -10.1]
 [  4.  464.  -41.   -8.1]
 [ 13.  400.  -35.   -8. ]]
