# Numpy 활용

In [16]:
import numpy as np

In [17]:
arr = np.array([[1,2,3],[4,5,6]]) # 2x3
print(arr)
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(arr.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [19]:
print(arr.reshape(1,6))

[[1 2 3 4 5 6]]


In [20]:
print(arr.reshape(3,1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [21]:
print(arr.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [22]:
print(arr.reshape(2,-1))

[[1 2 3]
 [4 5 6]]


In [23]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1.reshape(6,))

[1 2 3 4 5 6]


In [33]:
#문제 1
tensor = np.array(range(1,37)) #shape (3, 3, 4)
print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [40]:
# 문제 2 
# tensor 배열을 2차원 배열로 변형시켜봅시다. * 열의개수는 9

print(tensor.reshape(-1,9))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


### Flatten

In [35]:
print(arr.flatten())

[1 2 3 4 5 6]


In [37]:
print(arr.reshape(1,6).flatten())

[1 2 3 4 5 6]


In [38]:
print(arr.reshape(3,1,2).flatten())

[1 2 3 4 5 6]


In [42]:
print(tensor.reshape(3,3,4).flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


### Arange

In [46]:
# np.arange(size)
print(np.arange(30))  # np.array(range(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [47]:
# 간격지정(np.arange(start, end, step))
print(np.arange(0,10,2))

[0 2 4 6 8]


In [48]:
print(np.arange(0,2,0.2))

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [49]:
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


### Arange + Reshape

In [57]:
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [54]:
print(np.arange(0,6,0.2).reshape(3,2,5))

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


In [58]:
# 문제3 100~190, 10 shape(2,5)

print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [82]:
# 문제4 -2 ~ 2, 0.5, 3차원
print(np.arange(-2,2.1,0.5).reshape(1,3,3))


[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


### Zeros

In [90]:
print(np.zeros(shape=(5,),dtype=np.int8))

[0 0 0 0 0]


In [91]:
print(np.zeros((5),np.int8))

[0 0 0 0 0]


In [92]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


### Ones


In [97]:
print(np.ones(shape=(5,),dtype=np.int8))

[1 1 1 1 1]


In [98]:
print(np.ones((5),np.int8))

[1 1 1 1 1]


In [99]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


### Empty

In [102]:
# np.empty(shape, dtype)
print(np.empty(shape=(10,),dtype=np.int32))

[100 110 120 130 140 150 160 170 180 190]


In [103]:
print(np.empty((2,5),np.int8))

[[0 1 1 1 1]
 [1 1 1 1 1]]


### Zeros_like / Ones_like / Empty_like

In [106]:
# np.zeros_like(ndarray)
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [112]:
# np.ones_like(ndarray)
matrix = np.arange(-2,2,0.2).reshape(2,10)
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [114]:
# np.empty_like(ndarray)
matrix = np.empty(30).reshape(5,6)
print(np.empty_like(matrix))

[[0.  0.2 0.4 0.6 0.8 1. ]
 [1.2 1.4 1.6 1.8 2.  2.2]
 [2.4 2.6 2.8 3.  3.2 3.4]
 [3.6 3.8 4.  4.2 4.4 4.6]
 [4.8 5.  5.2 5.4 5.6 5.8]]


### Identity
- 단위 행렬 -  주대각선의 값이 1이고 나머지는 0인 정사각 행렬

In [117]:
# np.identity(size, dtype)
print(np.identity(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [120]:
print(np.identity(2,dtype=np.str_))

[['1' '']
 ['' '1']]


### Eye

In [122]:
# np.eye(size, M, k, dtype)
print(np.eye(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [125]:
# k : 대각선의 시작 위치를 입력받은 수 만큼 오른쪽으로 이동
# M : 보여지는 열의 개수를 지정
print(np.eye(5,k=2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [132]:
print(np.eye(5, M = 10, k = -1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [134]:
print(np.eye(5, M = 3, k = -1))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


### Full

In [135]:
# np.full((shape),value)
print(np.full((2,5),3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [137]:
print(np.full((5,4),5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [140]:
print(np.ones((3,3)) * 3)

print(np.full((3,3),3))


[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


### Random.randint
- 주어진 범위 안의 랜덤한 값을 뽑는 함수

In [151]:
# np.random,randint(range)
# 0~5까지 정수 중 하나 뽑기
print(np.random.randint(6))

3


In [161]:
# 1~19 까지의 정수 중 여러개 뽑기
print(np.random.randint(1,20,2))

[7 3]


In [153]:
import random
random.randint(0,10)

5

### Random.rand
- 랜덤한 값으로 채워지는 배열
- 표준정규분포 난수를 shape 형태의 배열로 생성
- 0 ~ 1 사이의 값을 가짐

In [162]:
# np.random.rand(shape)

print(np.random.rand(3))

[0.65811507 0.43580104 0.67783686]


In [163]:
print(np.random.rand(3,2))

[[0.62369848 0.13681362]
 [0.88415024 0.90671289]
 [0.50786484 0.06026608]]


### Random.randn
- 랜덤한 값으로 채워지는 배열
- 평균 0, 표준편차 1의 가우시안 표준정규분포 난수를 shape 형태의 배열로 생성

In [165]:
# np.random.randn(shpae)
print(np.random.randn(3))

[ 0.42558049 -0.53280889  0.50962813]


In [166]:
print(np.random.randn(3,2))

[[-0.66880838 -1.76327746]
 [-1.31849048  1.07158458]
 [ 0.62499651  1.20099994]]


## 연산함수
- 배열의 요소값들을 이용하여 연산을 할 수 있게 해주는 함수

### 합(sum)

In [175]:
# ndarray.sum()
matrix = np.arange(1,7).reshape(2,3)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [176]:
print(matrix.sum())

21


In [179]:
print(matrix.sum(axis=0)) # 행끼리

[5 7 9]


In [181]:
print(matrix.sum(axis=1)) # 열끼리

[ 6 15]


In [182]:
# 3차원 배열 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [187]:
print(tensor)

print(tensor.sum(axis=0))
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


In [195]:
tensor.sum(axis=0)  #np.sum(tensor)

array([[21, 24, 27],
       [30, 33, 36]])

In [193]:
np.sum(tensor, axis=0)

array([[21, 24, 27],
       [30, 33, 36]])

### 평균(mean)
- 합과 동일

In [190]:
# 2차원 배열 평균
print(matrix)

print(matrix.mean())       # 전체평균
print(matrix.mean(axis=0)) # 행끼리 평균(위 아래)
print(matrix.mean(axis=1)) # 열끼리 평균(좌 우)

[[1 2 3]
 [4 5 6]]
3.5
[2.5 3.5 4.5]
[2. 5.]


### 표준편차(std)
- 합, 평균과 동일

In [199]:
# 2차원 배열 표준 편차
print(matrix)

print(matrix.std())       # 전체표준편차
print(matrix.std(axis=0)) # 행끼리 표준편차(위 아래)
print(matrix.std(axis=1)) # 열끼리 표준편차(좌 우)

[[1 2 3]
 [4 5 6]]
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [203]:
import math
math.sqrt(((2.5-1)*(2.5-1) + (2.5-4)*(2.5-4)) / 2)

1.5

### 그 외 수학 연산자
- 지수(exp)
- 로그(log)
- 제곱근(sqrt)
- 삼각함수(sin)
- 삼각함수(cos)
- 삼각함수(tan)

In [207]:
print(np.exp(matrix))
print(np.log(matrix))
print(np.sqrt(matrix))
print(np.sin(matrix))
print(np.cos(matrix))
print(np.tan(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


### 배열 정렬(Sort)

In [212]:
# 1차원 배열 정렬
# randint를 사용하여 1~100 숫자 중 5개를 뽑아 배열 생성
vector = np.array([np.random.randint(1,100)
                    for n in range(5)])
print(vector)

print(np.sort(vector))       # 오름차순으로 정렬

print(np.sort(vector)[::-1]) # 내림차순으로 정렬(reverse 함수 따로 없음)

[51 26 35 75 41]
[26 35 41 51 75]
[75 51 41 35 26]


In [215]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [217]:
a = []
for i in range(5):
    a.append(i)
print(a)

[0, 1, 2, 3, 4]


In [221]:
# list 내 포문
list_ = [1,2,3,4,5,6,7,8,9,10]

list2_ = [num * 3 for num in list_ 
            if num % 2 == 1]

print(list2_)

[3, 9, 15, 21, 27]


In [225]:
# 2차원 배열 정렬
# randint를 사용하여 1~100 숫자 중 20개를 뽑아 배열 생성
matrix = np.array([np.random.randint(1,100)
                    for n in range(20)]).reshape(4,5)
print(matrix)

print(np.sort(matrix)) # 열 기준으로 정렬

print(np.sort(matrix, axis=0)) # 행 기준으로 정렬

[[41 23 18 46  1]
 [88  1 45 84 79]
 [66 68 20 18 34]
 [30 84 11 85 33]]
[[ 1 18 23 41 46]
 [ 1 45 79 84 88]
 [18 20 34 66 68]
 [11 30 33 84 85]]
[[30  1 11 18  1]
 [41 23 18 46 33]
 [66 68 20 84 34]
 [88 84 45 85 79]]


### 배열 합치기 (Vstack)
- 2개 이상의 배열을 수직으로 합체

In [229]:
# np.vstack([arr1,arr2])
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.vstack([vector1, vector2]))

[[1 2 3]
 [4 5 6]]


### 배열 합치기(Hstack)
- 2개 이상의 배열을 수평으로 합체

In [231]:
# np.hstack([arr1,arr2])
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.hstack([vector1, vector2]))

[[1]
 [2]
 [3]]
[[1 4]
 [2 5]
 [3 6]]


In [232]:
vector1 = np.array([1,2,3]) # [1,2,3]
vector2 = np.array([4,5,6]) # [4,5,6]
print(np.hstack([vector1, vector2])) # [1,2,3,4,5,6]

[1 2 3 4 5 6]


### 배열 합치기(Concatenate)
- 2개 이상의 배열을 수직, 수평으로 합체

In [244]:
# np.concatenate([arr1,arr2])
vector1 = np.array([[1,2,3]])
vector2 = np.array([[4,5,6]])
print(np.concatenate([vector1, vector2],axis=0))

[[1 2 3]
 [4 5 6]]


In [242]:
# np.concatenate([arr1,arr2])
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.concatenate([vector1, vector2],axis=1)) 

[[1 4]
 [2 5]
 [3 6]]


In [251]:
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.concatenate([matrix1, vector2], axis=1)) 

[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [253]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1,matrix2],axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [254]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1,matrix2],axis=1))

[[1 2 5 6]
 [3 4 7 8]]


### 행/열 바꾸기(transpose)
- 행과 열을 뒤집어 주는 함수

In [ ]:
# ndarray.transpose()
# ndarray.T

In [255]:
matrix3 = np.array([[5,6]])
print(matrix3)

[[5 6]]


In [256]:
print(matrix3.transpose())

[[5]
 [6]]


In [258]:
print(matrix3.shape, matrix3.transpose().shape)

(1, 2) (2, 1)


In [265]:
print(matrix3.T)
print(np.array([5,6]).T.shape)
print(np.array([[[5,6]]]).T.shape)

[[5]
 [6]]
(2,)
(2, 1, 1)


### Transpose + Concatenate
- 형태를 바꿔 서로 결합할 수 없는 배열을 합칠 수 있다.

In [261]:
print(np.concatenate([matrix1,matrix3]))

[[1 2]
 [3 4]
 [5 6]]


In [262]:
print(np.concatenate([matrix1,matrix3],axis=1)) # 수평으로 결합하기에 행의 갯수 오류

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [266]:
print(np.concatenate([matrix1,matrix3.T],axis=1))

[[1 2 5]
 [3 4 6]]


### 인덱스 반환 함수
- 최대값, 최소값의 인덱스 
- argmax, argmin (arg : argument)
- 인덱스는 값의 value를 뽑아주는 것이 아닌, 어느 위치에 존재하는지 말해주는 함수


In [267]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [268]:
print(np.argmax(a), np.argmin(a))

9 0


In [269]:
print(np.argmax(a, axis=0))

[1 1 1 1 1]


In [279]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]


In [281]:
print(np.argmax(b, axis=1))
print(np.argmin(b, axis=1))

[3 2 1]
[0 3 2]


In [282]:
print(np.argmax(b, axis=0))
print(np.argmin(b, axis=0))

[2 2 1 0]
[0 0 2 1]


### 배열 인덱싱(Fancy Index)
- 인덱스의 값을 가지는 배열을 통해 인덱싱

In [274]:
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]


In [275]:
print(a[b])

[4 5 6 7]


In [283]:
# 인덱스 반환 함수 + fancy indes
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]
9


In [284]:
print(a[b])

19
