# Numpy 배열 연산

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]


### 산술연산
- shape이 같은 배열은 연산 가능

In [15]:
# 모양이 같은 배열 연산
arr1 = np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2 = np.arange(11,17,dtype=np.float32).reshape(2,3)
print(arr1 + arr2) 
print(arr1 - arr2)
print(arr1 * arr2)
print(arr2 / arr1)  

[[12. 14. 16.]
 [18. 20. 22.]]
[[-10. -10. -10.]
 [-10. -10. -10.]]
[[11. 24. 39.]
 [56. 75. 96.]]
[[11.         6.         4.3333335]
 [ 3.5        3.         2.6666667]]


In [16]:
print(arr1 ** arr2) # 제곱
print(arr2 // arr1) # 몫
print(arr2 % arr1)  # 나머지

[[1.0000000e+00 4.0960000e+03 1.5943230e+06]
 [2.6843546e+08 3.0517578e+10 2.8211098e+12]]
[[11.  6.  4.]
 [ 3.  3.  2.]]
[[0. 0. 1.]
 [2. 0. 4.]]


### Numpy 연산 함수

In [29]:
# np.add(arr1,arr2)
np.add(arr1,arr2)
print(arr1,arr2)
print(np.add(arr1,arr2))


# np.subtract(arr1, arr2)
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

# np.multiply(arr1, arr2)
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

# np.divide(arr1, arr2)
print(arr2/arr1)
print(np.divide(arr1,arr2))

[[1. 2. 3.]
 [4. 5. 6.]] [[11. 12. 13.]
 [14. 15. 16.]]
[[12. 14. 16.]
 [18. 20. 22.]]
[[-10. -10. -10.]
 [-10. -10. -10.]]
[[-10. -10. -10.]
 [-10. -10. -10.]]
[[11. 24. 39.]
 [56. 75. 96.]]
[[11. 24. 39.]
 [56. 75. 96.]]
[[11.         6.         4.3333335]
 [ 3.5        3.         2.6666667]]
[[0.09090909 0.16666667 0.23076923]
 [0.2857143  0.33333334 0.375     ]]


### 산술연산
- Broadcasting

- 연산하고자 하는 배열의 모양이 다른 경우의 연산

In [27]:
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
print(arr3 + arr4)

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [32]:
# Broadcasting : shape이 다른 배열 간 연산 지원
# 배열과 스칼라의 연산
scalar = 10
vector = np.array([1,2,3])
print(scalar + vector)
print(scalar - vector)
print(scalar * vector)
print(scalar / vector)

[11 12 13]
[9 8 7]
[10 20 30]
[10.          5.          3.33333333]


In [35]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar + matrix)
print(scalar - matrix)
print(scalar * matrix)
print(scalar / matrix)
print(scalar // matrix)
print(scalar % matrix)

[[11 12 13]
 [14 15 16]]
[[9 8 7]
 [6 5 4]]
[[10 20 30]
 [40 50 60]]
[[10.          5.          3.33333333]
 [ 2.5         2.          1.66666667]]
[[10  5  3]
 [ 2  2  1]]
[[0 0 1]
 [2 0 4]]


In [45]:
# 벡터와 매트릭스의 연산
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix)
print(vector)
print(matrix + vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]]
[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [46]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(3,1)
print(matrix)
print(vector)
print(matrix + vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11]
 [12]
 [13]]
[[12 13 14]
 [16 17 18]
 [20 21 22]]


In [50]:
# 벡터와 벡터의 브로드캐스팅 연산
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)

print(arr1 + arr2)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [51]:
np.broadcast(arr1, arr2)

In [53]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

np.broadcast(arr3, arr4)

### 행렬 연산
- 수학에서의 행렬의 곱셈
- np.dot(arr1, arr2) 함수 사용

In [56]:
# 일반적인 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1 * arr2)

# bp.dot 사용 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T
print(np.dot(arr1, arr2))   

[1 4 9]
14


In [60]:
# np.dot(arr1,arr2) 함수

# np.dot(arr1,arr2)
print(np.dot(arr1,arr2))
# arr1.dot(arr2)
print(arr1.dot(arr2))
# arr1@arr2
print(arr1@arr2)

14
14
14


In [59]:
# 2차원 배열 행렬곱
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
